### ISSUE TITLE
tcomb-form-native with Node 10 not handling import statements

### ISSUE THREAD

**Issue by danascheider** [gcanti/tcomb-form-native#494]
### Summary

I was running Node version 6.x and when I added `import t from 'tcomb-form-native'` to one of my component files, I began getting errors in Travis Pro that said `Unexpected token import`. The output is shown at the bottom of this report.

I decided to address the problem by upgrading to the latest stable Node release since I heard support for ES6 was added in v9.x. After I did this, I began getting the second error (also pasted below).

### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.13
- react-native v0.55.4
- react v16.3.1
- Node.js v10.3.0

### Expected behaviour

Test suite should run

### Actual behaviour

Under Node v6.x, the error says `Unexpected token import`. Under Node v10.x, the error says `Unexpected identifier` and points to a line in tcomb-form-native/index.js.

### Steps to reproduce

1. Create a basic React Native app with tcomb-form-native using `create-react-native-app`
2. Add `import t from 'tcomb-form-native'` to the top of the App.js file
3. Run `yarn test`
4. See failures.

### Stack trace and console log

Under Node v6.x:
```
 FAIL  ./App.test.js
  ● Test suite failed to run
    /home/travis/build/danascheider/inview-login-service/node_modules/tcomb-form-native/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import t from "./lib";
                                                                                             ^^^^^^
    
    SyntaxError: Unexpected token import
    > 1 | import React from 'react';
      2 | import { StyleSheet, Text, View, Button } from 'react-native';
      3 | import t from 'tcomb-form-native';
      4 | import bootstrap from 'tcomb-form-native/lib/stylesheets/bootstrap.js';
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:316:17)
      at Object.<anonymous> (App.js:1:2116)
      at Object.<anonymous> (App.test.js:1:170)
```
Under Node v10.x:
```
  ● Test suite failed to run

    /Users/dana/Development/inview-login-service/node_modules/tcomb-form-native/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import t from "./lib";
                                                                                                    ^

    SyntaxError: Unexpected identifier

    > 1 | import React from 'react'
      2 | import { AppRegistry, Stylesheet, Text, View } from 'react-native'
      3 | import t from 'tcomb-form-native'
      4 | // import bootstrap from 'tcomb-form-native/lib/stylesheets/bootstrap.js'

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:316:17)
      at Object.<anonymous> (loginForm.js:1:2263)
```

**Comment by GokulDharumar** [comment]
we have the same issue with reactnativeapp.. any updates on this will help 
Thanks

**Comment by IanSaucy** [comment]
I'm also experiencing similar issues. Anyone else able to figure this out? I'm running Jest, ts-jest along with expo-jest since I'm running Expo. 
Error:
`\_\_tests\_\_/signup.spec.tsx
Test suite failed to run

    projectFolder\node_modules\tcomb-form-native\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import t from "./lib";
                                                                                                    ^

    SyntaxError: Unexpected identifier

       6 |     Text,
       7 | } from 'react-native';
    >  8 | import form from 'tcomb-form-native';
         | ^
       9 | import { Dropdown } from 'react-native-material-dropdown';
      10 | 
      11 | 

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (app/screens/Signup-Screen.tsx:8:1)`

**Comment by rpeg** [comment]
Still an issue with Jest + expo-jest on:

- tcomb-form-native v0.6.20
- Expo SDK 37 (react-native v0.61) 
- react v16.13.1
- node v10.17.0

**Comment by rpeg** [comment]
I don't suppose anyone has had any luck with a workaround yet? I've been trying various babel / jest config setups to no avail. I may have to abandon tcomb altogether if this isn't resolved.

**Comment by fadzb** [comment]
Im having a similar issue, seems like jest/babel isn't able to transform the js files from tcomb-form-native correctly. I have tried several different babel/jest config tweaks (explicitly defining transform options as well as transformIgnorePatterns) but no luck. 

Although not a proper solution at all, it is possible to mock the entire module from your jest tests. (as a temporary workaround) 

I got my tests to pass (following https://jestjs.io/docs/en/manual-mocks) by adding a folder adjacent to node_modules called `__mocks__` containing a single empty file called `tcomb-form-native.js` Bare in mind, mocking the entire module will be extremely limiting for any tests required to test some output of it's code.

I am clueless as to why babel/jest is struggling to compile the js properly. I notice the module uses `tape` for its unit tests. Could this (along with other internal dependencies) be causing the babel issues?

**Comment by drice** [comment]
try
```node
t = require('tcomb-form-native');
```
